#!/bin/bash

# Script pour lancer tous les services en mode développement
# Usage: chmod +x start-dev.sh && ./start-dev.sh

echo "🚀 Démarrage de tous les services en mode développement..."
echo ""
echo "Ouvre un nouvel onglet terminal pour chaque service :"
echo ""
echo "# Terminal 1 - API Gateway"
echo "cd api-gateway && npm run dev"
echo ""
echo "# Terminal 2 - Auth Service"
echo "cd services/auth-service && npm run dev"
echo ""
echo "# Terminal 3 - Workouts Service"
echo "cd services/workouts-service && npm run dev"
echo ""
echo "# Terminal 4 - Nutrition Service"
echo "cd services/nutrition-service && npm run dev"
echo ""
echo "# Terminal 5 - PR Service"
echo "cd services/pr-service && npm run dev"
echo ""
echo "# Terminal 6 - Templates Service"
echo "cd services/templates-service && npm run dev"
echo ""
echo "# Terminal 7 - Chatbot Service"
echo "cd services/chatbot-service && npm run dev"
echo ""
echo "Ou utilise un gestionnaire de processus comme 'concurrently' ou 'pm2'"
